# Generated by Django 6.0.6 on 2026-06-09 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeroporto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('codigo_iata', models.CharField(max_length=3, unique=True)),
                ('cidade', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Aeroporto',
                'verbose_name_plural': 'Aeroportos',
            },
        ),
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_voo', models.CharField(max_length=10, unique=True)),
                ('data_partida', models.DateTimeField()),
                ('data_chegada', models.DateTimeField()),
                ('capacidade', models.IntegerField()),
                ('preco_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('programado', 'Programado'), ('embarcando', 'Embarcando'), ('em_voo', 'Em Voo'), ('pousado', 'Pousado'), ('cancelado', 'Cancelado')], default='programado', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voos_chegada', to='sistema_passagens.aeroporto')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voos_partida', to='sistema_passagens.aeroporto')),
            ],
            options={
                'verbose_name': 'Voo',
                'verbose_name_plural': 'Voos',
            },
        ),
        migrations.CreateModel(
            name='Passagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passageiro_nome', models.CharField(max_length=150)),
                ('passageiro_cpf', models.CharField(max_length=14)),
                ('assento', models.CharField(max_length=5)),
                ('classe', models.CharField(choices=[('economica', 'Econômica'), ('executiva', 'Executiva'), ('primeira', 'Primeira Classe')], default='economica', max_length=20)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('reservada', 'Reservada'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='reservada', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('voo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passagens', to='sistema_passagens.voo')),
            ],
            options={
                'verbose_name': 'Passagem',
                'verbose_name_plural': 'Passagens',
            },
        ),
    ]
